### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by AMDmi3**

### CODE REVIEW

**Comment by pavel-odintsov** [comment]
Thanks so much!

**Comment by pavel-odintsov** [comment]
A have added additional code for backward compatibility: https://github.com/FastVPSEestiOu/fastnetmon/commit/3d581014e63f57ca8bd4bc18fc1cd9b0c2759492

Because everywhere we build release package without any options to cmake. If anybody want debug package he should specify it explicitly with:
```bash
cmake -DCMAKE_BUILD_TYPE=Debug ..
```

**Comment by AMDmi3** [comment]
Well my rule is to never make any assumptions and let users explicitly set all flags they need. But this seems to be OK, as it probably allows to set CMAKE_BUILD_TYPE="" and not append any flags.

**Comment by pavel-odintsov** [comment]
Good, thanks for feedback.

**Pull request merged**
